
services:
  mosquitto:
    container_name: mosquitto_container2
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iottri
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  manager:
    image: emqx/ekuiper-manager:1.8.0
    container_name: ekuiper_manager
    ports:
      - "9082:9082"
    restart: unless-stopped
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
    networks:
      - iottri

  ekuiper:
    image: lfedge/ekuiper:1.8.0
    ports:
      - "9081:9081"
    container_name: ekuiperr
    hostname: ekuiper
    restart: unless-stopped
    user: root
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto_container2:1883"
    networks:
      - iottri

  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    container_name: nats_container
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks:
    - iottri
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=veljko
      - DOCKER_INFLUXDB_INIT_PASSWORD=InternetOfThings
      - DOCKER_INFLUXDB_INIT_ORG=IotOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=AirQualityData
      - DOCKER_INFLUXDB_INIT_RETENTION=0
    networks:
      - iottri
  grafana:
    image: grafana/grafana-oss:8.4.3
    depends_on: 
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=veljko
      - GF_SECURITY_ADMIN_PASSWORD=InternetOfThings
    networks:
      - iottri

networks:
  iottri:
    name: iottri
