
services:
  mosquitto:
    container_name: mosquitto_container2
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iottri
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  eKuipermanager:
    image: emqx/ekuiper-manager:1.8.0
    container_name: eKuipermanager_container
    ports:
      - "9082:9082"
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
    networks:
      - iottri

  ekuiper:
    image: lfedge/ekuiper:1.8.0
    ports:
      - "9081:9081"
    container_name: ekuiper_container
    hostname: ekuiper
    volumes:
      - ./eKuiper/data/init.json:/kuiper/data/init.json:ro
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto_container2:1883"
    networks:
      - iottri

  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    container_name: nats_container
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks:
    - iottri

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=veljko
      - DOCKER_INFLUXDB_INIT_PASSWORD=InternetOfThings
      - DOCKER_INFLUXDB_INIT_ORG=IotOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=AirQualityData
      - DOCKER_INFLUXDB_INIT_RETENTION=0
    networks:
      - iottri
  grafana:
    image: grafana/grafana-oss:8.4.3
    depends_on: 
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - iottri
  sensor:
    container_name: sensor_container_iot3
    build:
      context: Sensor
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    networks:
      - iottri
    depends_on:
      - mosquitto
    volumes:
      - ./AirQuality.csv:/sensor/config/AirQuality.csv
  filter:
    container_name: filter_container
    build:
      context: Filter
      dockerfile: Dockerfile
    ports:
      - "6061:6061"
    networks:
      - iottri
    depends_on:
      - mosquitto
  dashboard:
    container_name: dashboard_container
    build:
      context: dashboard
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto
    networks:
      - iottri
  command:
    container_name: command_container
    build:
      context: command
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mosquitto
    networks:
      - iottri
networks:
  iottri:
    name: iottri
